//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPolicyAgent.Opa.OpenApi.Models.Requests
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using OpenPolicyAgent.Opa.OpenApi.Models.Components;
    using OpenPolicyAgent.Opa.OpenApi.Utils;

    /// <summary>
    /// The query, input, and other settings for partial evaluation.
    /// </summary>
    public class CompileQueryWithPartialEvaluationRequestApplicationJSONRequestBody
    {

        /// <summary>
        /// Additional options to use during partial evaluation. Only the disableInlining option is currently supported in OPA. EOPA may support additional options.
        /// </summary>
        [JsonProperty("options")]
        public CompileOptions? Options { get; set; }

        /// <summary>
        /// The terms to treat as unknown during partial evaluation.
        /// </summary>
        [JsonProperty("unknowns")]
        public List<string>? Unknowns { get; set; }

        /// <summary>
        /// Arbitrary JSON used within your policies by accessing `input`
        /// </summary>
        [JsonProperty("input")]
        public Input? Input { get; set; }
    }
}