//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPolicyAgent.Opa.OpenApi.Models.Requests
{
    using System;
    using System.Net.Http;
    using OpenPolicyAgent.Opa.OpenApi.Models.Components;
    using OpenPolicyAgent.Opa.OpenApi.Utils;

    public class CompileQueryWithPartialEvaluationResponse
    {

        /// <summary>
        /// HTTP response content type for this operation
        /// </summary>
        public string? ContentType { get; set; } = default!;

        /// <summary>
        /// HTTP response status code for this operation
        /// </summary>
        public int StatusCode { get; set; } = default!;

        /// <summary>
        /// Raw HTTP response; suitable for custom response parsing
        /// </summary>
        public HttpResponseMessage RawResponse { get; set; } = default!;

        /// <summary>
        /// Successful response
        /// </summary>
        public CompileResultJSON? CompileResultJSON { get; set; }

        /// <summary>
        /// Successful response
        /// </summary>
        public CompileResultMultitarget? CompileResultMultitarget { get; set; }

        /// <summary>
        /// Successful response
        /// </summary>
        public CompileResultUCAST? CompileResultUCAST { get; set; }

        /// <summary>
        /// Successful response
        /// </summary>
        public CompileResultSQL? CompileResultSQL { get; set; }
    }
}