//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPolicyAgent.Opa.OpenApi.Models.Components
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using OpenPolicyAgent.Opa.OpenApi.Models.Components;
    using OpenPolicyAgent.Opa.OpenApi.Utils;

    /// <summary>
    /// All batched policy executions succeeded.<br/>
    /// 
    /// <remarks>
    /// The server also returns 200 if the path refers to an undefined document. In this case, responses will be empty.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public class BatchSuccessfulPolicyEvaluation
    {

        [JsonProperty("batch_decision_id")]
        public string? BatchDecisionId { get; set; }

        /// <summary>
        /// If query metrics are enabled, this field contains query performance metrics collected during the parse, compile, and evaluation steps.
        /// </summary>
        [JsonProperty("metrics")]
        public Dictionary<string, object>? Metrics { get; set; }

        [JsonProperty("responses")]
        public Dictionary<string, SuccessfulPolicyResponse>? Responses { get; set; }
    }
}