//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPolicyAgent.Opa.OpenApi.Models.Components
{
    using OpenPolicyAgent.Opa.OpenApi.Utils;

    /// <summary>
    /// UCAST JSON object describing the conditions under which the query is true.
    /// </summary>
    public class CompileResultMultitargetQuery
    {
    }
}