//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPolicyAgent.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using OpenPolicyAgent.Opa.OpenApi.Models.Components;
    using OpenPolicyAgent.Opa.OpenApi.Utils;

    public class Errors
    {

        [JsonProperty("code")]
        public string Code { get; set; } = default!;

        [JsonProperty("message")]
        public string Message { get; set; } = default!;

        [JsonProperty("location")]
        public Models.Components.Location? Location { get; set; }
    }
}