//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPolicyAgent.Opa.OpenApi.Models.Components
{
    using Newtonsoft.Json;
    using OpenPolicyAgent.Opa.OpenApi.Utils;

    public class Revision
    {

        [JsonProperty("revision")]
        public string RevisionValue { get; set; } = default!;
    }
}