//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenPolicyAgent.Opa.OpenApi.Models.Components
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using OpenPolicyAgent.Opa.OpenApi.Models.Errors;
    using OpenPolicyAgent.Opa.OpenApi.Utils;

    public class ServerError
    {

        [JsonProperty("code")]
        public string Code { get; set; } = default!;

        [JsonProperty("message")]
        public string Message { get; set; } = default!;

        [JsonProperty("errors")]
        public List<ServerErrorErrors>? Errors { get; set; }

        [JsonProperty("decision_id")]
        public string? DecisionId { get; set; }
    }
}